### ISSUE TITLE
any example about how to integrated with elasticsearch?

### ISSUE THREAD

**Issue by xycloud** [dataux/dataux#68]

**Comment by araddon** [comment]
I will update the example on how to do it and upload asap.

**Comment by araddon** [comment]
I updated this readme quite a bit, can you take a peek and see if that helps?

https://github.com/dataux/dataux/tree/master/backends/elasticsearch

**Comment by xycloud** [comment]
thanks, I am not good at go, could you directly provide a binary version of dataux, I and other people may wanna quickly try this awesome proxy

**Comment by araddon** [comment]
I am committed do doing binary releases:  https://github.com/dataux/dataux/releases  and docker releases.   Ill update the elasticsearch example to include usage of binary release.

**Comment by araddon** [comment]
Ill upload a binary copy of githubarchive import tool as well, or possibly a docker elasticsearch with examples.

**Comment by xycloud** [comment]
got some error:

```
2017/11/27 10:10:57.543500 apply_schema.go:75: [DEBUG] 0xc420137900:server_schema InfoSchema P:0xc4201379a0  adding schema "server_schema" s==v?true
2017/11/27 10:10:57.543632 schema.go:400: [DEBUG] could not load table Could not find that table: columns
2017/11/27 10:10:57.543735 apply_schema.go:67: [DEBUG] 0xc420137900:server_schema InfoSchema P:0xc4201379a0  adding table "workers"
2017/11/27 10:10:57.543760 registry.go:212: [WARN] Can't add duplicate schema "server_schema"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x18c7531]

goroutine 1 [running]:
github.com/dataux/dataux/vendor/github.com/sony/sonyflake.(*Sonyflake).NextID(0x0, 0x0, 0x0, 0x0)
	/home/aaron/go/src/github.com/dataux/dataux/vendor/github.com/sony/sonyflake/sonyflake.go:89 +0x41
github.com/dataux/dataux/planner.NextId(0xc420285e98, 0xc42023bda0, 0x156a3a3)
	/home/aaron/go/src/github.com/dataux/dataux/planner/plan_server.go:62 +0x2d
github.com/dataux/dataux/planner.NewPlannerGrid(0x2, 0xc420118820, 0xc42023be10)
	/home/aaron/go/src/github.com/dataux/dataux/planner/plan_server.go:99 +0x26
github.com/dataux/dataux/models.(*ServerCtx).Init(0xc420257320, 0xc420257320, 0x3)
	/home/aaron/go/src/github.com/dataux/dataux/models/serverctx.go:71 +0x165
github.com/dataux/dataux/proxy.RunDaemon(0x1, 0x3)
	/home/aaron/go/src/github.com/dataux/dataux/proxy/server.go:65 +0x105
main.main()
	/home/aaron/go/src/github.com/dataux/dataux/main.go:83 +0xab
```
